USE MASTER
GO

DROP DATABASE IF EXISTS FPL_DaoTao
CREATE DATABASE FPL_DAOTAO
GO

USE FPL_DaoTao
GO

DROP TABLE IF EXISTS USERS
CREATE TABLE USERS (
	USERNAME VARCHAR(7) PRIMARY KEY,
	[PASSWORD] NVARCHAR(12) NOT NULL,
	[ROLE] NVARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS STUDENTS
CREATE TABLE STUDENTS (
	MASV NVARCHAR(5) PRIMARY KEY,
	[NAME] NVARCHAR(30) NULL,
	EMAIL NVARCHAR(50) NULL,
	PHONE VARCHAR(10) NULL,
	GENDER BIT NULL,
	[ADDRESS] NVARCHAR(50) NULL,
	HINH NVARCHAR(30) NULL
);

DROP TABLE IF EXISTS GRADES
CREATE TABLE GRADES (
	ID NVARCHAR(5) PRIMARY KEY,
	MASV NVARCHAR(5) NULL,
	ENGLISHSCORE FLOAT NULL,
	ITSCORE FLOAT NULL,
	PESCORE FLOAT NULL,
	AVGSCORE FLOAT NULL

	CONSTRAINT PK_GRADES_MASV FOREIGN KEY (MASV) REFERENCES STUDENTS(MASV)
);

INSERT INTO USERS VALUES 
('SV12345', '123456','STUDENT'),
('GV12345', '123456','TEACHER'),
('DT12345', '123456','MANAGER'),
('PS23577', '123456','STUDENT')

SELECT * FROM USERS
SELECT * FROM GRADES
SELECT * FROM STUDENTS